from pathlib import Path
import hashlib,json,subprocess,shutil
R=Path('.')
p=R/'src/routes/__root.tsx';s=p.read_text().replace('import { reportLovableError } from "../lib/lovable-error-reporting";', 'import { reportRuntimeError } from "../lib/runtime-diagnostics";').replace('reportLovableError(error, { boundary: "tanstack_root_error_component" });','reportRuntimeError(error, "route-boundary");').replace('  console.error(error);\n  const router','  const router');p.write_text(s)
(R/'src/lib/lovable-error-reporting.ts').unlink()
p=R/'package.json';j=json.loads(p.read_text());j['name']='proof-and-state-website';j['devDependencies'].pop('@lovable.dev/vite-tanstack-config');j['devDependencies']['@tanstack/devtools-vite']='0.8.3';j['devDependencies']['lightningcss']='1.33.0';j['scripts']['test:toolchain']='bun test tests/toolchain.test.ts';p.write_text(json.dumps(j,indent=2)+'\n')
p=R/'bun.lock';s=p.read_text().replace('"name": "tanstack_start_ts"','"name": "proof-and-state-website"').replace('        "@lovable.dev/vite-tanstack-config": "^2.15.0",\n','').replace('        "@eslint/js": "^9.32.0",','        "@eslint/js": "^9.32.0",\n        "@tanstack/devtools-vite": "0.8.3",\n        "lightningcss": "1.33.0",');s='\n'.join(line for line in s.splitlines() if not line.lstrip().startswith('"@lovable.dev/vite-tanstack-config":'))+'\n';p.write_text(s)
(R/'bunfig.toml').write_text('[install]\nsaveTextLockfile = true\n# 24-hour supply-chain guard. No vendor-specific exemptions.\nminimumReleaseAge = 86400\n')
p=R/'tsconfig.json';j=json.loads(p.read_text());j['include']+=['tools/**/*.ts'];p.write_text(json.dumps(j,indent=2)+'\n')
(R/'docs/history').mkdir(parents=True,exist_ok=True)
(R/'docs/history/initial-design-plan.md').write_text('> Historical initial design brief, preserved from the imported scaffold. Not the current runtime specification. Product status, routes, hosting, metadata and branding have since changed. Use src/, Wrangler and current CI.\n\n'+(R/'.lovable/plan.md').read_text())
shutil.rmtree(R/'.lovable')
p=R/'README.md';s=p.read_text().replace('Lovable is not part of the production request or deployment path.', 'Build configuration, client diagnostics and deployment are owned here. No Lovable package or editor bridge is required. Historical design provenance is retained under `docs/history/`.');s=s.replace('bunx tsc --noEmit\nbun run build','bunx tsc --noEmit\nbun run test:toolchain\npython3 -m unittest discover -s tests -v\npython3 scripts/verify_branding.py --assets public\nbun run build\nbash scripts/check_built_branding.sh');s=s.replace('The production build is emitted','The dev server binds to `127.0.0.1:8080`; external exposure requires an intentional CLI override. Only `VITE_` environment variables are public. See `docs/TOOLCHAIN.md` for the capability audit and diagnostics boundaries.\n\nThe production build is emitted');p.write_text(s)
p=R/'.gitignore';p.write_text(p.read_text()+'\n# Local verification output\nbranding-evidence/\n__pycache__/\n')
base='484be40385f44223a3b748b77cafa13ae80ddd60'
paths=['src/styles.css','src/router.tsx','src/server.ts','src/start.ts','src/lib/error-capture.ts','src/lib/error-page.ts','src/components/ps/nav.tsx','src/components/ps/footer.tsx','src/components/ps/brand.tsx','src/components/ps/theme-toggle.tsx','src/content/site.ts','src/lib/seo.ts','scripts/branding-contract.json','public/_headers','wrangler.jsonc']
generated={'compatibility_date':'2026-08-30','$schema':'node_modules/wrangler/config-schema.json','name':'proof-and-state-website','main':'index.mjs','compatibility_flags':['nodejs_compat'],'workers_dev':True,'no_bundle':True,'assets':{'binding':'ASSETS','directory':'../public'},'rules':[{'type':'ESModule','globs':['**/*.mjs','**/*.js']}],'routes':[{'pattern':'proofandstate.com','custom_domain':True},{'pattern':'www.proofandstate.com','custom_domain':True}],'observability':{'enabled':True,'head_sampling_rate':1}}
contract={'source_commit':base,'audit_run':34805597832,'generated_wrangler':generated,'protected_source_sha256':{p:hashlib.sha256(subprocess.check_output(['git','show',base+':'+p])).hexdigest() for p in paths}}
(R/'tools/toolchain-baseline.json').write_text(json.dumps(contract,indent=2)+'\n')
for wf in ['ci.yml','deploy-cloudflare.yml']:
 p=R/'.github/workflows'/wf;s=p.read_text().replace('actions/checkout@v4','actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683').replace('oven-sh/setup-bun@v2','oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6').replace('bun-version: latest','bun-version: 1.4.2');s=s.replace('      - name: Branding regression tests','      - name: Owned toolchain unit tests\n        run: bun run test:toolchain\n\n      - name: Branding regression tests');s=s.replace('          bunx tsc --noEmit\n','          bunx tsc --noEmit\n          bun run test:toolchain\n');s=s.replace('run: bash scripts/check_built_branding.sh','run: |\n          python3 scripts/verify_toolchain.py --built --report branding-evidence/toolchain.json\n          bash scripts/check_built_branding.sh');s=s.replace('      - "src/**"','      - "src/**"\n      - "tools/**"\n      - "bunfig.toml"');
 if wf=='deploy-cloudflare.yml':
  s=s.replace('      - name: Preserve production branding evidence','      - name: Verify deployed owned bundles\n        run: python3 scripts/verify_toolchain.py --built --origin https://proofandstate.com --report branding-evidence/production-toolchain.json\n\n      - name: Preserve production branding evidence')
 p.write_text(s)
# This preparation is deliberately one-shot and never part of normal builds.
(R/'.github/workflows/audit-owned-toolchain.yml').unlink()
