/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DonestateRouteImport } from './routes/donestate'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ArchitectureIndexRouteImport } from './routes/architecture.index'
import { Route as ArchitectureAuthorityModelRouteImport } from './routes/architecture.authority-model'
import { Route as ArchitectureStateModelRouteImport } from './routes/architecture.state-model'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as DevelopersIntegrationsRouteImport } from './routes/developers.integrations'
import { Route as DevelopersQuickstartRouteImport } from './routes/developers.quickstart'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PrinciplesIndexRouteImport } from './routes/principles.index'
import { Route as PrinciplesSlugRouteImport } from './routes/principles.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsAgentproofRouteImport } from './routes/products.agentproof'
import { Route as ProductsDonestateRouteImport } from './routes/products.donestate'
import { Route as ProductsOpstruthRouteImport } from './routes/products.opstruth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonestateRoute = DonestateRouteImport.update({
  id: '/donestate',
  path: '/donestate',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureIndexRoute = ArchitectureIndexRouteImport.update({
  id: '/architecture/',
  path: '/architecture/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureAuthorityModelRoute =
  ArchitectureAuthorityModelRouteImport.update({
    id: '/architecture/authority-model',
    path: '/architecture/authority-model',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchitectureStateModelRoute = ArchitectureStateModelRouteImport.update({
  id: '/architecture/state-model',
  path: '/architecture/state-model',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIntegrationsRoute = DevelopersIntegrationsRouteImport.update({
  id: '/developers/integrations',
  path: '/developers/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersQuickstartRoute = DevelopersQuickstartRouteImport.update({
  id: '/developers/quickstart',
  path: '/developers/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesIndexRoute = PrinciplesIndexRouteImport.update({
  id: '/principles/',
  path: '/principles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesSlugRoute = PrinciplesSlugRouteImport.update({
  id: '/principles/$slug',
  path: '/principles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAgentproofRoute = ProductsAgentproofRouteImport.update({
  id: '/products/agentproof',
  path: '/products/agentproof',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDonestateRoute = ProductsDonestateRouteImport.update({
  id: '/products/donestate',
  path: '/products/donestate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOpstruthRoute = ProductsOpstruthRouteImport.update({
  id: '/products/opstruth',
  path: '/products/opstruth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/donestate': typeof DonestateRoute
  '/glossary': typeof GlossaryRoute
  '/open-source': typeof OpenSourceRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/architecture/authority-model': typeof ArchitectureAuthorityModelRoute
  '/architecture/state-model': typeof ArchitectureStateModelRoute
  '/developers/integrations': typeof DevelopersIntegrationsRoute
  '/developers/quickstart': typeof DevelopersQuickstartRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/principles/$slug': typeof PrinciplesSlugRoute
  '/products/agentproof': typeof ProductsAgentproofRoute
  '/products/donestate': typeof ProductsDonestateRoute
  '/products/opstruth': typeof ProductsOpstruthRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/principles/': typeof PrinciplesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/donestate': typeof DonestateRoute
  '/glossary': typeof GlossaryRoute
  '/open-source': typeof OpenSourceRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/architecture/authority-model': typeof ArchitectureAuthorityModelRoute
  '/architecture/state-model': typeof ArchitectureStateModelRoute
  '/developers/integrations': typeof DevelopersIntegrationsRoute
  '/developers/quickstart': typeof DevelopersQuickstartRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/principles/$slug': typeof PrinciplesSlugRoute
  '/products/agentproof': typeof ProductsAgentproofRoute
  '/products/donestate': typeof ProductsDonestateRoute
  '/products/opstruth': typeof ProductsOpstruthRoute
  '/architecture': typeof ArchitectureIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/principles': typeof PrinciplesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/donestate': typeof DonestateRoute
  '/glossary': typeof GlossaryRoute
  '/open-source': typeof OpenSourceRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/architecture/authority-model': typeof ArchitectureAuthorityModelRoute
  '/architecture/state-model': typeof ArchitectureStateModelRoute
  '/developers/integrations': typeof DevelopersIntegrationsRoute
  '/developers/quickstart': typeof DevelopersQuickstartRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/principles/$slug': typeof PrinciplesSlugRoute
  '/products/agentproof': typeof ProductsAgentproofRoute
  '/products/donestate': typeof ProductsDonestateRoute
  '/products/opstruth': typeof ProductsOpstruthRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/principles/': typeof PrinciplesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/donestate'
    | '/glossary'
    | '/open-source'
    | '/security'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/architecture/authority-model'
    | '/architecture/state-model'
    | '/developers/integrations'
    | '/developers/quickstart'
    | '/legal/privacy'
    | '/legal/terms'
    | '/principles/$slug'
    | '/products/agentproof'
    | '/products/donestate'
    | '/products/opstruth'
    | '/architecture/'
    | '/developers/'
    | '/principles/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/donestate'
    | '/glossary'
    | '/open-source'
    | '/security'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/architecture/authority-model'
    | '/architecture/state-model'
    | '/developers/integrations'
    | '/developers/quickstart'
    | '/legal/privacy'
    | '/legal/terms'
    | '/principles/$slug'
    | '/products/agentproof'
    | '/products/donestate'
    | '/products/opstruth'
    | '/architecture'
    | '/developers'
    | '/principles'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/donestate'
    | '/glossary'
    | '/open-source'
    | '/security'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/architecture/authority-model'
    | '/architecture/state-model'
    | '/developers/integrations'
    | '/developers/quickstart'
    | '/legal/privacy'
    | '/legal/terms'
    | '/principles/$slug'
    | '/products/agentproof'
    | '/products/donestate'
    | '/products/opstruth'
    | '/architecture/'
    | '/developers/'
    | '/principles/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  DonestateRoute: typeof DonestateRoute
  GlossaryRoute: typeof GlossaryRoute
  OpenSourceRoute: typeof OpenSourceRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TrustRoute: typeof TrustRoute
  ArchitectureAuthorityModelRoute: typeof ArchitectureAuthorityModelRoute
  ArchitectureStateModelRoute: typeof ArchitectureStateModelRoute
  DevelopersIntegrationsRoute: typeof DevelopersIntegrationsRoute
  DevelopersQuickstartRoute: typeof DevelopersQuickstartRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PrinciplesSlugRoute: typeof PrinciplesSlugRoute
  ProductsAgentproofRoute: typeof ProductsAgentproofRoute
  ProductsDonestateRoute: typeof ProductsDonestateRoute
  ProductsOpstruthRoute: typeof ProductsOpstruthRoute
  ArchitectureIndexRoute: typeof ArchitectureIndexRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
  PrinciplesIndexRoute: typeof PrinciplesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donestate': {
      id: '/donestate'
      path: '/donestate'
      fullPath: '/donestate'
      preLoaderRoute: typeof DonestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/': {
      id: '/architecture/'
      path: '/architecture'
      fullPath: '/architecture/'
      preLoaderRoute: typeof ArchitectureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/authority-model': {
      id: '/architecture/authority-model'
      path: '/architecture/authority-model'
      fullPath: '/architecture/authority-model'
      preLoaderRoute: typeof ArchitectureAuthorityModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/state-model': {
      id: '/architecture/state-model'
      path: '/architecture/state-model'
      fullPath: '/architecture/state-model'
      preLoaderRoute: typeof ArchitectureStateModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/integrations': {
      id: '/developers/integrations'
      path: '/developers/integrations'
      fullPath: '/developers/integrations'
      preLoaderRoute: typeof DevelopersIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/quickstart': {
      id: '/developers/quickstart'
      path: '/developers/quickstart'
      fullPath: '/developers/quickstart'
      preLoaderRoute: typeof DevelopersQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles/': {
      id: '/principles/'
      path: '/principles'
      fullPath: '/principles/'
      preLoaderRoute: typeof PrinciplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles/$slug': {
      id: '/principles/$slug'
      path: '/principles/$slug'
      fullPath: '/principles/$slug'
      preLoaderRoute: typeof PrinciplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/agentproof': {
      id: '/products/agentproof'
      path: '/products/agentproof'
      fullPath: '/products/agentproof'
      preLoaderRoute: typeof ProductsAgentproofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/donestate': {
      id: '/products/donestate'
      path: '/products/donestate'
      fullPath: '/products/donestate'
      preLoaderRoute: typeof ProductsDonestateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/opstruth': {
      id: '/products/opstruth'
      path: '/products/opstruth'
      fullPath: '/products/opstruth'
      preLoaderRoute: typeof ProductsOpstruthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  DonestateRoute: DonestateRoute,
  GlossaryRoute: GlossaryRoute,
  OpenSourceRoute: OpenSourceRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TrustRoute: TrustRoute,
  ArchitectureAuthorityModelRoute: ArchitectureAuthorityModelRoute,
  ArchitectureStateModelRoute: ArchitectureStateModelRoute,
  DevelopersIntegrationsRoute: DevelopersIntegrationsRoute,
  DevelopersQuickstartRoute: DevelopersQuickstartRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PrinciplesSlugRoute: PrinciplesSlugRoute,
  ProductsAgentproofRoute: ProductsAgentproofRoute,
  ProductsDonestateRoute: ProductsDonestateRoute,
  ProductsOpstruthRoute: ProductsOpstruthRoute,
  ArchitectureIndexRoute: ArchitectureIndexRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
  PrinciplesIndexRoute: PrinciplesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
